// Code generated by protoc-gen-go.
// source: luluBattle.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	luluBattle.proto

It has these top-level messages:
	PlayerInfo
	BaseAttr
	BornInfo
	FrameRoleData
	RoleMove
	ExpCN
	BuffCN
	C2GSLogin
	GS2CLoginRet
	C2GSChooseRole
	GS2CChooseRoleRet
	C2GSStartGame
	GS2CStartGameRet
	C2GSSyncPkg
	GS2CSyncPkg
*/
package pb

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type ErrorCode int32

const (
	ErrorCode_SUCCESS        ErrorCode = 1
	ErrorCode_FAIL           ErrorCode = 2
	ErrorCode_ACCOUNT_ERROR  ErrorCode = 3
	ErrorCode_PASSWORD_ERROR ErrorCode = 4
	ErrorCode_NICKNAME_EXIST ErrorCode = 5
)

var ErrorCode_name = map[int32]string{
	1: "SUCCESS",
	2: "FAIL",
	3: "ACCOUNT_ERROR",
	4: "PASSWORD_ERROR",
	5: "NICKNAME_EXIST",
}
var ErrorCode_value = map[string]int32{
	"SUCCESS":        1,
	"FAIL":           2,
	"ACCOUNT_ERROR":  3,
	"PASSWORD_ERROR": 4,
	"NICKNAME_EXIST": 5,
}

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}
func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}
func (x *ErrorCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ErrorCode_value, data, "ErrorCode")
	if err != nil {
		return err
	}
	*x = ErrorCode(value)
	return nil
}

type GameMode int32

const (
	GameMode_GameMode_Idle GameMode = 1
	GameMode_Single        GameMode = 2
)

var GameMode_name = map[int32]string{
	1: "GameMode_Idle",
	2: "Single",
}
var GameMode_value = map[string]int32{
	"GameMode_Idle": 1,
	"Single":        2,
}

func (x GameMode) Enum() *GameMode {
	p := new(GameMode)
	*p = x
	return p
}
func (x GameMode) String() string {
	return proto.EnumName(GameMode_name, int32(x))
}
func (x *GameMode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GameMode_value, data, "GameMode")
	if err != nil {
		return err
	}
	*x = GameMode(value)
	return nil
}

type MoveStatus int32

const (
	MoveStatus_MoveStatus_Idle MoveStatus = 1
	MoveStatus_Walk            MoveStatus = 2
	MoveStatus_Run             MoveStatus = 3
)

var MoveStatus_name = map[int32]string{
	1: "MoveStatus_Idle",
	2: "Walk",
	3: "Run",
}
var MoveStatus_value = map[string]int32{
	"MoveStatus_Idle": 1,
	"Walk":            2,
	"Run":             3,
}

func (x MoveStatus) Enum() *MoveStatus {
	p := new(MoveStatus)
	*p = x
	return p
}
func (x MoveStatus) String() string {
	return proto.EnumName(MoveStatus_name, int32(x))
}
func (x *MoveStatus) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MoveStatus_value, data, "MoveStatus")
	if err != nil {
		return err
	}
	*x = MoveStatus(value)
	return nil
}

type PlayerInfo struct {
	OID              *uint32 `protobuf:"varint,1,req" json:"OID,omitempty"`
	NickName         *string `protobuf:"bytes,2,req" json:"NickName,omitempty"`
	HeadIcon         *string `protobuf:"bytes,3,req" json:"HeadIcon,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PlayerInfo) Reset()         { *m = PlayerInfo{} }
func (m *PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*PlayerInfo) ProtoMessage()    {}

func (m *PlayerInfo) GetOID() uint32 {
	if m != nil && m.OID != nil {
		return *m.OID
	}
	return 0
}

func (m *PlayerInfo) GetNickName() string {
	if m != nil && m.NickName != nil {
		return *m.NickName
	}
	return ""
}

func (m *PlayerInfo) GetHeadIcon() string {
	if m != nil && m.HeadIcon != nil {
		return *m.HeadIcon
	}
	return ""
}

type BaseAttr struct {
	Hp               *uint32 `protobuf:"varint,1,req" json:"Hp,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BaseAttr) Reset()         { *m = BaseAttr{} }
func (m *BaseAttr) String() string { return proto.CompactTextString(m) }
func (*BaseAttr) ProtoMessage()    {}

func (m *BaseAttr) GetHp() uint32 {
	if m != nil && m.Hp != nil {
		return *m.Hp
	}
	return 0
}

type BornInfo struct {
	OID              *uint32   `protobuf:"varint,1,req" json:"OID,omitempty"`
	NickName         *string   `protobuf:"bytes,2,req" json:"NickName,omitempty"`
	RoleID           *int32    `protobuf:"varint,3,req" json:"RoleID,omitempty"`
	PosX             *int32    `protobuf:"varint,4,req" json:"PosX,omitempty"`
	PosY             *int32    `protobuf:"varint,5,req" json:"PosY,omitempty"`
	Attr             *BaseAttr `protobuf:"bytes,6,req" json:"Attr,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *BornInfo) Reset()         { *m = BornInfo{} }
func (m *BornInfo) String() string { return proto.CompactTextString(m) }
func (*BornInfo) ProtoMessage()    {}

func (m *BornInfo) GetOID() uint32 {
	if m != nil && m.OID != nil {
		return *m.OID
	}
	return 0
}

func (m *BornInfo) GetNickName() string {
	if m != nil && m.NickName != nil {
		return *m.NickName
	}
	return ""
}

func (m *BornInfo) GetRoleID() int32 {
	if m != nil && m.RoleID != nil {
		return *m.RoleID
	}
	return 0
}

func (m *BornInfo) GetPosX() int32 {
	if m != nil && m.PosX != nil {
		return *m.PosX
	}
	return 0
}

func (m *BornInfo) GetPosY() int32 {
	if m != nil && m.PosY != nil {
		return *m.PosY
	}
	return 0
}

func (m *BornInfo) GetAttr() *BaseAttr {
	if m != nil {
		return m.Attr
	}
	return nil
}

type FrameRoleData struct {
	PlayerID         *uint32   `protobuf:"varint,1,req" json:"PlayerID,omitempty"`
	Attr             *BaseAttr `protobuf:"bytes,2,req" json:"Attr,omitempty"`
	Move             *RoleMove `protobuf:"bytes,3,req" json:"Move,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *FrameRoleData) Reset()         { *m = FrameRoleData{} }
func (m *FrameRoleData) String() string { return proto.CompactTextString(m) }
func (*FrameRoleData) ProtoMessage()    {}

func (m *FrameRoleData) GetPlayerID() uint32 {
	if m != nil && m.PlayerID != nil {
		return *m.PlayerID
	}
	return 0
}

func (m *FrameRoleData) GetAttr() *BaseAttr {
	if m != nil {
		return m.Attr
	}
	return nil
}

func (m *FrameRoleData) GetMove() *RoleMove {
	if m != nil {
		return m.Move
	}
	return nil
}

type RoleMove struct {
	Status           *MoveStatus `protobuf:"varint,1,req,enum=pb.MoveStatus" json:"Status,omitempty"`
	Rot              *uint32     `protobuf:"varint,2,req" json:"Rot,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *RoleMove) Reset()         { *m = RoleMove{} }
func (m *RoleMove) String() string { return proto.CompactTextString(m) }
func (*RoleMove) ProtoMessage()    {}

func (m *RoleMove) GetStatus() MoveStatus {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return MoveStatus_MoveStatus_Idle
}

func (m *RoleMove) GetRot() uint32 {
	if m != nil && m.Rot != nil {
		return *m.Rot
	}
	return 0
}

type ExpCN struct {
	Status           *uint32 `protobuf:"varint,1,req" json:"Status,omitempty"`
	PosX             *uint32 `protobuf:"varint,2,req,name=pos_x" json:"pos_x,omitempty"`
	PosY             *uint32 `protobuf:"varint,3,req,name=pos_y" json:"pos_y,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ExpCN) Reset()         { *m = ExpCN{} }
func (m *ExpCN) String() string { return proto.CompactTextString(m) }
func (*ExpCN) ProtoMessage()    {}

func (m *ExpCN) GetStatus() uint32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

func (m *ExpCN) GetPosX() uint32 {
	if m != nil && m.PosX != nil {
		return *m.PosX
	}
	return 0
}

func (m *ExpCN) GetPosY() uint32 {
	if m != nil && m.PosY != nil {
		return *m.PosY
	}
	return 0
}

type BuffCN struct {
	Status           *uint32 `protobuf:"varint,1,req" json:"Status,omitempty"`
	PosX             *uint32 `protobuf:"varint,2,req,name=pos_x" json:"pos_x,omitempty"`
	PosY             *uint32 `protobuf:"varint,3,req,name=pos_y" json:"pos_y,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BuffCN) Reset()         { *m = BuffCN{} }
func (m *BuffCN) String() string { return proto.CompactTextString(m) }
func (*BuffCN) ProtoMessage()    {}

func (m *BuffCN) GetStatus() uint32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

func (m *BuffCN) GetPosX() uint32 {
	if m != nil && m.PosX != nil {
		return *m.PosX
	}
	return 0
}

func (m *BuffCN) GetPosY() uint32 {
	if m != nil && m.PosY != nil {
		return *m.PosY
	}
	return 0
}

// ///////////////////////////////////////////////////////////////////
type C2GSLogin struct {
	Account          *string `protobuf:"bytes,1,req,name=account" json:"account,omitempty"`
	Password         *string `protobuf:"bytes,2,req,name=password" json:"password,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *C2GSLogin) Reset()         { *m = C2GSLogin{} }
func (m *C2GSLogin) String() string { return proto.CompactTextString(m) }
func (*C2GSLogin) ProtoMessage()    {}

func (m *C2GSLogin) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *C2GSLogin) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

type GS2CLoginRet struct {
	ErrorCode        *ErrorCode  `protobuf:"varint,1,req,name=errorCode,enum=pb.ErrorCode" json:"errorCode,omitempty"`
	PlayerInfo       *PlayerInfo `protobuf:"bytes,2,opt,name=playerInfo" json:"playerInfo,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *GS2CLoginRet) Reset()         { *m = GS2CLoginRet{} }
func (m *GS2CLoginRet) String() string { return proto.CompactTextString(m) }
func (*GS2CLoginRet) ProtoMessage()    {}

func (m *GS2CLoginRet) GetErrorCode() ErrorCode {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return ErrorCode_SUCCESS
}

func (m *GS2CLoginRet) GetPlayerInfo() *PlayerInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

type C2GSChooseRole struct {
	NickName         *string `protobuf:"bytes,1,req" json:"NickName,omitempty"`
	HeadIcon         *string `protobuf:"bytes,2,req" json:"HeadIcon,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *C2GSChooseRole) Reset()         { *m = C2GSChooseRole{} }
func (m *C2GSChooseRole) String() string { return proto.CompactTextString(m) }
func (*C2GSChooseRole) ProtoMessage()    {}

func (m *C2GSChooseRole) GetNickName() string {
	if m != nil && m.NickName != nil {
		return *m.NickName
	}
	return ""
}

func (m *C2GSChooseRole) GetHeadIcon() string {
	if m != nil && m.HeadIcon != nil {
		return *m.HeadIcon
	}
	return ""
}

type GS2CChooseRoleRet struct {
	ErrorCode        *ErrorCode  `protobuf:"varint,1,req,name=errorCode,enum=pb.ErrorCode" json:"errorCode,omitempty"`
	PlayerInfo       *PlayerInfo `protobuf:"bytes,2,req,name=playerInfo" json:"playerInfo,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *GS2CChooseRoleRet) Reset()         { *m = GS2CChooseRoleRet{} }
func (m *GS2CChooseRoleRet) String() string { return proto.CompactTextString(m) }
func (*GS2CChooseRoleRet) ProtoMessage()    {}

func (m *GS2CChooseRoleRet) GetErrorCode() ErrorCode {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return ErrorCode_SUCCESS
}

func (m *GS2CChooseRoleRet) GetPlayerInfo() *PlayerInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

type C2GSStartGame struct {
	Mode             *GameMode `protobuf:"varint,1,req,enum=pb.GameMode" json:"Mode,omitempty"`
	MapID            *int32    `protobuf:"varint,2,req" json:"MapID,omitempty"`
	RoleID           *int32    `protobuf:"varint,3,req" json:"RoleID,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *C2GSStartGame) Reset()         { *m = C2GSStartGame{} }
func (m *C2GSStartGame) String() string { return proto.CompactTextString(m) }
func (*C2GSStartGame) ProtoMessage()    {}

func (m *C2GSStartGame) GetMode() GameMode {
	if m != nil && m.Mode != nil {
		return *m.Mode
	}
	return GameMode_GameMode_Idle
}

func (m *C2GSStartGame) GetMapID() int32 {
	if m != nil && m.MapID != nil {
		return *m.MapID
	}
	return 0
}

func (m *C2GSStartGame) GetRoleID() int32 {
	if m != nil && m.RoleID != nil {
		return *m.RoleID
	}
	return 0
}

type GS2CStartGameRet struct {
	Mode             *GameMode   `protobuf:"varint,1,req,enum=pb.GameMode" json:"Mode,omitempty"`
	MapID            *int32      `protobuf:"varint,2,req" json:"MapID,omitempty"`
	Players          []*BornInfo `protobuf:"bytes,3,rep" json:"Players,omitempty"`
	Exp              []*ExpCN    `protobuf:"bytes,4,rep" json:"Exp,omitempty"`
	Buff             []*BuffCN   `protobuf:"bytes,5,rep" json:"Buff,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *GS2CStartGameRet) Reset()         { *m = GS2CStartGameRet{} }
func (m *GS2CStartGameRet) String() string { return proto.CompactTextString(m) }
func (*GS2CStartGameRet) ProtoMessage()    {}

func (m *GS2CStartGameRet) GetMode() GameMode {
	if m != nil && m.Mode != nil {
		return *m.Mode
	}
	return GameMode_GameMode_Idle
}

func (m *GS2CStartGameRet) GetMapID() int32 {
	if m != nil && m.MapID != nil {
		return *m.MapID
	}
	return 0
}

func (m *GS2CStartGameRet) GetPlayers() []*BornInfo {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *GS2CStartGameRet) GetExp() []*ExpCN {
	if m != nil {
		return m.Exp
	}
	return nil
}

func (m *GS2CStartGameRet) GetBuff() []*BuffCN {
	if m != nil {
		return m.Buff
	}
	return nil
}

type C2GSSyncPkg struct {
	ClientAct        *uint32   `protobuf:"varint,1,opt" json:"ClientAct,omitempty"`
	Trs              *RoleMove `protobuf:"bytes,2,opt" json:"Trs,omitempty"`
	Act              *uint32   `protobuf:"varint,3,req" json:"Act,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *C2GSSyncPkg) Reset()         { *m = C2GSSyncPkg{} }
func (m *C2GSSyncPkg) String() string { return proto.CompactTextString(m) }
func (*C2GSSyncPkg) ProtoMessage()    {}

func (m *C2GSSyncPkg) GetClientAct() uint32 {
	if m != nil && m.ClientAct != nil {
		return *m.ClientAct
	}
	return 0
}

func (m *C2GSSyncPkg) GetTrs() *RoleMove {
	if m != nil {
		return m.Trs
	}
	return nil
}

func (m *C2GSSyncPkg) GetAct() uint32 {
	if m != nil && m.Act != nil {
		return *m.Act
	}
	return 0
}

type GS2CSyncPkg struct {
	Act              *uint32          `protobuf:"varint,1,req" json:"Act,omitempty"`
	Role             []*FrameRoleData `protobuf:"bytes,2,rep" json:"Role,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *GS2CSyncPkg) Reset()         { *m = GS2CSyncPkg{} }
func (m *GS2CSyncPkg) String() string { return proto.CompactTextString(m) }
func (*GS2CSyncPkg) ProtoMessage()    {}

func (m *GS2CSyncPkg) GetAct() uint32 {
	if m != nil && m.Act != nil {
		return *m.Act
	}
	return 0
}

func (m *GS2CSyncPkg) GetRole() []*FrameRoleData {
	if m != nil {
		return m.Role
	}
	return nil
}

func init() {
	proto.RegisterEnum("pb.ErrorCode", ErrorCode_name, ErrorCode_value)
	proto.RegisterEnum("pb.GameMode", GameMode_name, GameMode_value)
	proto.RegisterEnum("pb.MoveStatus", MoveStatus_name, MoveStatus_value)
}
