// Code generated by protoc-gen-go.
// source: luluBattle.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	luluBattle.proto

It has these top-level messages:
	PlayerInfo
	RoleTrs
	EnergeCN
	BuffCN
	C2GSLogin
	GS2CLoginRet
	C2GSChooseRole
	GS2CChooseRoleRet
	GS2CEnterGame
	GSSyncPkgRecv
	GSSyncPkgSend
*/
package pb

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type ErrorCode int32

const (
	ErrorCode_SUCCESS        ErrorCode = 1
	ErrorCode_FAIL           ErrorCode = 2
	ErrorCode_ACCOUNT_ERROR  ErrorCode = 3
	ErrorCode_PASSWORD_ERROR ErrorCode = 4
	ErrorCode_NICKNAME_EXIST ErrorCode = 5
)

var ErrorCode_name = map[int32]string{
	1: "SUCCESS",
	2: "FAIL",
	3: "ACCOUNT_ERROR",
	4: "PASSWORD_ERROR",
	5: "NICKNAME_EXIST",
}
var ErrorCode_value = map[string]int32{
	"SUCCESS":        1,
	"FAIL":           2,
	"ACCOUNT_ERROR":  3,
	"PASSWORD_ERROR": 4,
	"NICKNAME_EXIST": 5,
}

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}
func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}
func (x *ErrorCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ErrorCode_value, data, "ErrorCode")
	if err != nil {
		return err
	}
	*x = ErrorCode(value)
	return nil
}

type PlayerInfo struct {
	OID              *int32  `protobuf:"varint,1,req" json:"OID,omitempty"`
	NickName         *string `protobuf:"bytes,2,req" json:"NickName,omitempty"`
	HeadIcon         *string `protobuf:"bytes,3,req" json:"HeadIcon,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PlayerInfo) Reset()         { *m = PlayerInfo{} }
func (m *PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*PlayerInfo) ProtoMessage()    {}

func (m *PlayerInfo) GetOID() int32 {
	if m != nil && m.OID != nil {
		return *m.OID
	}
	return 0
}

func (m *PlayerInfo) GetNickName() string {
	if m != nil && m.NickName != nil {
		return *m.NickName
	}
	return ""
}

func (m *PlayerInfo) GetHeadIcon() string {
	if m != nil && m.HeadIcon != nil {
		return *m.HeadIcon
	}
	return ""
}

type RoleTrs struct {
	PosX             *uint32 `protobuf:"varint,1,req,name=pos_x" json:"pos_x,omitempty"`
	PosY             *uint32 `protobuf:"varint,2,req,name=pos_y" json:"pos_y,omitempty"`
	Rot              *uint32 `protobuf:"varint,3,req,name=rot" json:"rot,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RoleTrs) Reset()         { *m = RoleTrs{} }
func (m *RoleTrs) String() string { return proto.CompactTextString(m) }
func (*RoleTrs) ProtoMessage()    {}

func (m *RoleTrs) GetPosX() uint32 {
	if m != nil && m.PosX != nil {
		return *m.PosX
	}
	return 0
}

func (m *RoleTrs) GetPosY() uint32 {
	if m != nil && m.PosY != nil {
		return *m.PosY
	}
	return 0
}

func (m *RoleTrs) GetRot() uint32 {
	if m != nil && m.Rot != nil {
		return *m.Rot
	}
	return 0
}

type EnergeCN struct {
	PosX             *uint32 `protobuf:"varint,1,req,name=pos_x" json:"pos_x,omitempty"`
	PosY             *uint32 `protobuf:"varint,2,req,name=pos_y" json:"pos_y,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *EnergeCN) Reset()         { *m = EnergeCN{} }
func (m *EnergeCN) String() string { return proto.CompactTextString(m) }
func (*EnergeCN) ProtoMessage()    {}

func (m *EnergeCN) GetPosX() uint32 {
	if m != nil && m.PosX != nil {
		return *m.PosX
	}
	return 0
}

func (m *EnergeCN) GetPosY() uint32 {
	if m != nil && m.PosY != nil {
		return *m.PosY
	}
	return 0
}

type BuffCN struct {
	PosX             *uint32 `protobuf:"varint,1,req,name=pos_x" json:"pos_x,omitempty"`
	PosY             *uint32 `protobuf:"varint,2,req,name=pos_y" json:"pos_y,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BuffCN) Reset()         { *m = BuffCN{} }
func (m *BuffCN) String() string { return proto.CompactTextString(m) }
func (*BuffCN) ProtoMessage()    {}

func (m *BuffCN) GetPosX() uint32 {
	if m != nil && m.PosX != nil {
		return *m.PosX
	}
	return 0
}

func (m *BuffCN) GetPosY() uint32 {
	if m != nil && m.PosY != nil {
		return *m.PosY
	}
	return 0
}

// ///////////////////////////////////////////////////////////////////
type C2GSLogin struct {
	Account          *string `protobuf:"bytes,1,req,name=account" json:"account,omitempty"`
	Password         *string `protobuf:"bytes,2,req,name=password" json:"password,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *C2GSLogin) Reset()         { *m = C2GSLogin{} }
func (m *C2GSLogin) String() string { return proto.CompactTextString(m) }
func (*C2GSLogin) ProtoMessage()    {}

func (m *C2GSLogin) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *C2GSLogin) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

type GS2CLoginRet struct {
	ErrorCode        *ErrorCode  `protobuf:"varint,1,req,name=errorCode,enum=pb.ErrorCode" json:"errorCode,omitempty"`
	PlayerInfo       *PlayerInfo `protobuf:"bytes,2,opt,name=playerInfo" json:"playerInfo,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *GS2CLoginRet) Reset()         { *m = GS2CLoginRet{} }
func (m *GS2CLoginRet) String() string { return proto.CompactTextString(m) }
func (*GS2CLoginRet) ProtoMessage()    {}

func (m *GS2CLoginRet) GetErrorCode() ErrorCode {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return ErrorCode_SUCCESS
}

func (m *GS2CLoginRet) GetPlayerInfo() *PlayerInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

type C2GSChooseRole struct {
	NickName         *string `protobuf:"bytes,1,req" json:"NickName,omitempty"`
	HeadIcon         *string `protobuf:"bytes,2,req" json:"HeadIcon,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *C2GSChooseRole) Reset()         { *m = C2GSChooseRole{} }
func (m *C2GSChooseRole) String() string { return proto.CompactTextString(m) }
func (*C2GSChooseRole) ProtoMessage()    {}

func (m *C2GSChooseRole) GetNickName() string {
	if m != nil && m.NickName != nil {
		return *m.NickName
	}
	return ""
}

func (m *C2GSChooseRole) GetHeadIcon() string {
	if m != nil && m.HeadIcon != nil {
		return *m.HeadIcon
	}
	return ""
}

type GS2CChooseRoleRet struct {
	ErrorCode        *ErrorCode  `protobuf:"varint,1,req,name=errorCode,enum=pb.ErrorCode" json:"errorCode,omitempty"`
	PlayerInfo       *PlayerInfo `protobuf:"bytes,2,req,name=playerInfo" json:"playerInfo,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *GS2CChooseRoleRet) Reset()         { *m = GS2CChooseRoleRet{} }
func (m *GS2CChooseRoleRet) String() string { return proto.CompactTextString(m) }
func (*GS2CChooseRoleRet) ProtoMessage()    {}

func (m *GS2CChooseRoleRet) GetErrorCode() ErrorCode {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return ErrorCode_SUCCESS
}

func (m *GS2CChooseRoleRet) GetPlayerInfo() *PlayerInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

type GS2CEnterGame struct {
	RoomID           *string  `protobuf:"bytes,1,req" json:"RoomID,omitempty"`
	BornTrs          *RoleTrs `protobuf:"bytes,2,req" json:"BornTrs,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *GS2CEnterGame) Reset()         { *m = GS2CEnterGame{} }
func (m *GS2CEnterGame) String() string { return proto.CompactTextString(m) }
func (*GS2CEnterGame) ProtoMessage()    {}

func (m *GS2CEnterGame) GetRoomID() string {
	if m != nil && m.RoomID != nil {
		return *m.RoomID
	}
	return ""
}

func (m *GS2CEnterGame) GetBornTrs() *RoleTrs {
	if m != nil {
		return m.BornTrs
	}
	return nil
}

type GSSyncPkgRecv struct {
	ClientAct        *uint32  `protobuf:"varint,1,opt" json:"ClientAct,omitempty"`
	Trs              *RoleTrs `protobuf:"bytes,2,opt" json:"Trs,omitempty"`
	Act              *uint32  `protobuf:"varint,3,req" json:"Act,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *GSSyncPkgRecv) Reset()         { *m = GSSyncPkgRecv{} }
func (m *GSSyncPkgRecv) String() string { return proto.CompactTextString(m) }
func (*GSSyncPkgRecv) ProtoMessage()    {}

func (m *GSSyncPkgRecv) GetClientAct() uint32 {
	if m != nil && m.ClientAct != nil {
		return *m.ClientAct
	}
	return 0
}

func (m *GSSyncPkgRecv) GetTrs() *RoleTrs {
	if m != nil {
		return m.Trs
	}
	return nil
}

func (m *GSSyncPkgRecv) GetAct() uint32 {
	if m != nil && m.Act != nil {
		return *m.Act
	}
	return 0
}

type GSSyncPkgSend struct {
	Act              *uint32   `protobuf:"varint,1,req" json:"Act,omitempty"`
	Trs              *RoleTrs  `protobuf:"bytes,2,req" json:"Trs,omitempty"`
	Energe           *EnergeCN `protobuf:"bytes,3,req" json:"Energe,omitempty"`
	Buff             *BuffCN   `protobuf:"bytes,4,req" json:"Buff,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *GSSyncPkgSend) Reset()         { *m = GSSyncPkgSend{} }
func (m *GSSyncPkgSend) String() string { return proto.CompactTextString(m) }
func (*GSSyncPkgSend) ProtoMessage()    {}

func (m *GSSyncPkgSend) GetAct() uint32 {
	if m != nil && m.Act != nil {
		return *m.Act
	}
	return 0
}

func (m *GSSyncPkgSend) GetTrs() *RoleTrs {
	if m != nil {
		return m.Trs
	}
	return nil
}

func (m *GSSyncPkgSend) GetEnerge() *EnergeCN {
	if m != nil {
		return m.Energe
	}
	return nil
}

func (m *GSSyncPkgSend) GetBuff() *BuffCN {
	if m != nil {
		return m.Buff
	}
	return nil
}

func init() {
	proto.RegisterEnum("pb.ErrorCode", ErrorCode_name, ErrorCode_value)
}
