// Code generated by protoc-gen-go.
// source: luluBattle.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	luluBattle.proto

It has these top-level messages:
	C2GSReqSyncTime
*/
package pb

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

// ///////////////////////////////////////////////////////////
type C2GSReqSyncTime struct {
	Time             *int64 `protobuf:"varint,1,req,name=time" json:"time,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *C2GSReqSyncTime) Reset()         { *m = C2GSReqSyncTime{} }
func (m *C2GSReqSyncTime) String() string { return proto.CompactTextString(m) }
func (*C2GSReqSyncTime) ProtoMessage()    {}

func (m *C2GSReqSyncTime) GetTime() int64 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func init() {
}
