// Code generated by protoc-gen-go.
// source: luluBattle.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	luluBattle.proto

It has these top-level messages:
	PlayerInfo
	FrameRoleData
	RoleMove
	EnergeCN
	BuffCN
	C2GSLogin
	GS2CLoginRet
	C2GSChooseRole
	GS2CChooseRoleRet
	GS2CEnterGame
	GSSyncPkgRecv
	GSSyncPkgSend
*/
package pb

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type ErrorCode int32

const (
	ErrorCode_SUCCESS        ErrorCode = 1
	ErrorCode_FAIL           ErrorCode = 2
	ErrorCode_ACCOUNT_ERROR  ErrorCode = 3
	ErrorCode_PASSWORD_ERROR ErrorCode = 4
	ErrorCode_NICKNAME_EXIST ErrorCode = 5
)

var ErrorCode_name = map[int32]string{
	1: "SUCCESS",
	2: "FAIL",
	3: "ACCOUNT_ERROR",
	4: "PASSWORD_ERROR",
	5: "NICKNAME_EXIST",
}
var ErrorCode_value = map[string]int32{
	"SUCCESS":        1,
	"FAIL":           2,
	"ACCOUNT_ERROR":  3,
	"PASSWORD_ERROR": 4,
	"NICKNAME_EXIST": 5,
}

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}
func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}
func (x *ErrorCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ErrorCode_value, data, "ErrorCode")
	if err != nil {
		return err
	}
	*x = ErrorCode(value)
	return nil
}

type MoveStatus int32

const (
	MoveStatus_Idle MoveStatus = 1
	MoveStatus_Walk MoveStatus = 2
	MoveStatus_Run  MoveStatus = 3
)

var MoveStatus_name = map[int32]string{
	1: "Idle",
	2: "Walk",
	3: "Run",
}
var MoveStatus_value = map[string]int32{
	"Idle": 1,
	"Walk": 2,
	"Run":  3,
}

func (x MoveStatus) Enum() *MoveStatus {
	p := new(MoveStatus)
	*p = x
	return p
}
func (x MoveStatus) String() string {
	return proto.EnumName(MoveStatus_name, int32(x))
}
func (x *MoveStatus) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MoveStatus_value, data, "MoveStatus")
	if err != nil {
		return err
	}
	*x = MoveStatus(value)
	return nil
}

type PlayerInfo struct {
	OID              *int32  `protobuf:"varint,1,req" json:"OID,omitempty"`
	NickName         *string `protobuf:"bytes,2,req" json:"NickName,omitempty"`
	HeadIcon         *string `protobuf:"bytes,3,req" json:"HeadIcon,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PlayerInfo) Reset()         { *m = PlayerInfo{} }
func (m *PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*PlayerInfo) ProtoMessage()    {}

func (m *PlayerInfo) GetOID() int32 {
	if m != nil && m.OID != nil {
		return *m.OID
	}
	return 0
}

func (m *PlayerInfo) GetNickName() string {
	if m != nil && m.NickName != nil {
		return *m.NickName
	}
	return ""
}

func (m *PlayerInfo) GetHeadIcon() string {
	if m != nil && m.HeadIcon != nil {
		return *m.HeadIcon
	}
	return ""
}

type FrameRoleData struct {
	PlayerID         *uint32   `protobuf:"varint,1,req" json:"PlayerID,omitempty"`
	Hp               *uint32   `protobuf:"varint,2,req" json:"Hp,omitempty"`
	Move             *RoleMove `protobuf:"bytes,3,req" json:"Move,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *FrameRoleData) Reset()         { *m = FrameRoleData{} }
func (m *FrameRoleData) String() string { return proto.CompactTextString(m) }
func (*FrameRoleData) ProtoMessage()    {}

func (m *FrameRoleData) GetPlayerID() uint32 {
	if m != nil && m.PlayerID != nil {
		return *m.PlayerID
	}
	return 0
}

func (m *FrameRoleData) GetHp() uint32 {
	if m != nil && m.Hp != nil {
		return *m.Hp
	}
	return 0
}

func (m *FrameRoleData) GetMove() *RoleMove {
	if m != nil {
		return m.Move
	}
	return nil
}

type RoleMove struct {
	Status           *MoveStatus `protobuf:"varint,1,req,enum=pb.MoveStatus" json:"Status,omitempty"`
	Rot              *uint32     `protobuf:"varint,2,req" json:"Rot,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *RoleMove) Reset()         { *m = RoleMove{} }
func (m *RoleMove) String() string { return proto.CompactTextString(m) }
func (*RoleMove) ProtoMessage()    {}

func (m *RoleMove) GetStatus() MoveStatus {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return MoveStatus_Idle
}

func (m *RoleMove) GetRot() uint32 {
	if m != nil && m.Rot != nil {
		return *m.Rot
	}
	return 0
}

type EnergeCN struct {
	PosX             *uint32 `protobuf:"varint,1,req,name=pos_x" json:"pos_x,omitempty"`
	PosY             *uint32 `protobuf:"varint,2,req,name=pos_y" json:"pos_y,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *EnergeCN) Reset()         { *m = EnergeCN{} }
func (m *EnergeCN) String() string { return proto.CompactTextString(m) }
func (*EnergeCN) ProtoMessage()    {}

func (m *EnergeCN) GetPosX() uint32 {
	if m != nil && m.PosX != nil {
		return *m.PosX
	}
	return 0
}

func (m *EnergeCN) GetPosY() uint32 {
	if m != nil && m.PosY != nil {
		return *m.PosY
	}
	return 0
}

type BuffCN struct {
	PosX             *uint32 `protobuf:"varint,1,req,name=pos_x" json:"pos_x,omitempty"`
	PosY             *uint32 `protobuf:"varint,2,req,name=pos_y" json:"pos_y,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BuffCN) Reset()         { *m = BuffCN{} }
func (m *BuffCN) String() string { return proto.CompactTextString(m) }
func (*BuffCN) ProtoMessage()    {}

func (m *BuffCN) GetPosX() uint32 {
	if m != nil && m.PosX != nil {
		return *m.PosX
	}
	return 0
}

func (m *BuffCN) GetPosY() uint32 {
	if m != nil && m.PosY != nil {
		return *m.PosY
	}
	return 0
}

// ///////////////////////////////////////////////////////////////////
type C2GSLogin struct {
	Account          *string `protobuf:"bytes,1,req,name=account" json:"account,omitempty"`
	Password         *string `protobuf:"bytes,2,req,name=password" json:"password,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *C2GSLogin) Reset()         { *m = C2GSLogin{} }
func (m *C2GSLogin) String() string { return proto.CompactTextString(m) }
func (*C2GSLogin) ProtoMessage()    {}

func (m *C2GSLogin) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *C2GSLogin) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

type GS2CLoginRet struct {
	ErrorCode        *ErrorCode  `protobuf:"varint,1,req,name=errorCode,enum=pb.ErrorCode" json:"errorCode,omitempty"`
	PlayerInfo       *PlayerInfo `protobuf:"bytes,2,opt,name=playerInfo" json:"playerInfo,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *GS2CLoginRet) Reset()         { *m = GS2CLoginRet{} }
func (m *GS2CLoginRet) String() string { return proto.CompactTextString(m) }
func (*GS2CLoginRet) ProtoMessage()    {}

func (m *GS2CLoginRet) GetErrorCode() ErrorCode {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return ErrorCode_SUCCESS
}

func (m *GS2CLoginRet) GetPlayerInfo() *PlayerInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

type C2GSChooseRole struct {
	NickName         *string `protobuf:"bytes,1,req" json:"NickName,omitempty"`
	HeadIcon         *string `protobuf:"bytes,2,req" json:"HeadIcon,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *C2GSChooseRole) Reset()         { *m = C2GSChooseRole{} }
func (m *C2GSChooseRole) String() string { return proto.CompactTextString(m) }
func (*C2GSChooseRole) ProtoMessage()    {}

func (m *C2GSChooseRole) GetNickName() string {
	if m != nil && m.NickName != nil {
		return *m.NickName
	}
	return ""
}

func (m *C2GSChooseRole) GetHeadIcon() string {
	if m != nil && m.HeadIcon != nil {
		return *m.HeadIcon
	}
	return ""
}

type GS2CChooseRoleRet struct {
	ErrorCode        *ErrorCode  `protobuf:"varint,1,req,name=errorCode,enum=pb.ErrorCode" json:"errorCode,omitempty"`
	PlayerInfo       *PlayerInfo `protobuf:"bytes,2,req,name=playerInfo" json:"playerInfo,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *GS2CChooseRoleRet) Reset()         { *m = GS2CChooseRoleRet{} }
func (m *GS2CChooseRoleRet) String() string { return proto.CompactTextString(m) }
func (*GS2CChooseRoleRet) ProtoMessage()    {}

func (m *GS2CChooseRoleRet) GetErrorCode() ErrorCode {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return ErrorCode_SUCCESS
}

func (m *GS2CChooseRoleRet) GetPlayerInfo() *PlayerInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

type GS2CEnterGame struct {
	RoomID           *string `protobuf:"bytes,1,req" json:"RoomID,omitempty"`
	PlayerID         *int32  `protobuf:"varint,2,req" json:"PlayerID,omitempty"`
	Nickname         *string `protobuf:"bytes,3,req" json:"Nickname,omitempty"`
	HeadIcon         *string `protobuf:"bytes,4,req" json:"HeadIcon,omitempty"`
	PosX             *int32  `protobuf:"varint,5,req" json:"PosX,omitempty"`
	PosY             *int32  `protobuf:"varint,6,req" json:"PosY,omitempty"`
	Hp               *uint32 `protobuf:"varint,7,req" json:"Hp,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GS2CEnterGame) Reset()         { *m = GS2CEnterGame{} }
func (m *GS2CEnterGame) String() string { return proto.CompactTextString(m) }
func (*GS2CEnterGame) ProtoMessage()    {}

func (m *GS2CEnterGame) GetRoomID() string {
	if m != nil && m.RoomID != nil {
		return *m.RoomID
	}
	return ""
}

func (m *GS2CEnterGame) GetPlayerID() int32 {
	if m != nil && m.PlayerID != nil {
		return *m.PlayerID
	}
	return 0
}

func (m *GS2CEnterGame) GetNickname() string {
	if m != nil && m.Nickname != nil {
		return *m.Nickname
	}
	return ""
}

func (m *GS2CEnterGame) GetHeadIcon() string {
	if m != nil && m.HeadIcon != nil {
		return *m.HeadIcon
	}
	return ""
}

func (m *GS2CEnterGame) GetPosX() int32 {
	if m != nil && m.PosX != nil {
		return *m.PosX
	}
	return 0
}

func (m *GS2CEnterGame) GetPosY() int32 {
	if m != nil && m.PosY != nil {
		return *m.PosY
	}
	return 0
}

func (m *GS2CEnterGame) GetHp() uint32 {
	if m != nil && m.Hp != nil {
		return *m.Hp
	}
	return 0
}

type GSSyncPkgRecv struct {
	ClientAct        *uint32   `protobuf:"varint,1,opt" json:"ClientAct,omitempty"`
	Trs              *RoleMove `protobuf:"bytes,2,opt" json:"Trs,omitempty"`
	Act              *uint32   `protobuf:"varint,3,req" json:"Act,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *GSSyncPkgRecv) Reset()         { *m = GSSyncPkgRecv{} }
func (m *GSSyncPkgRecv) String() string { return proto.CompactTextString(m) }
func (*GSSyncPkgRecv) ProtoMessage()    {}

func (m *GSSyncPkgRecv) GetClientAct() uint32 {
	if m != nil && m.ClientAct != nil {
		return *m.ClientAct
	}
	return 0
}

func (m *GSSyncPkgRecv) GetTrs() *RoleMove {
	if m != nil {
		return m.Trs
	}
	return nil
}

func (m *GSSyncPkgRecv) GetAct() uint32 {
	if m != nil && m.Act != nil {
		return *m.Act
	}
	return 0
}

type GSSyncPkgSend struct {
	Act              *uint32          `protobuf:"varint,1,req" json:"Act,omitempty"`
	Role             []*FrameRoleData `protobuf:"bytes,2,rep" json:"Role,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *GSSyncPkgSend) Reset()         { *m = GSSyncPkgSend{} }
func (m *GSSyncPkgSend) String() string { return proto.CompactTextString(m) }
func (*GSSyncPkgSend) ProtoMessage()    {}

func (m *GSSyncPkgSend) GetAct() uint32 {
	if m != nil && m.Act != nil {
		return *m.Act
	}
	return 0
}

func (m *GSSyncPkgSend) GetRole() []*FrameRoleData {
	if m != nil {
		return m.Role
	}
	return nil
}

func init() {
	proto.RegisterEnum("pb.ErrorCode", ErrorCode_name, ErrorCode_value)
	proto.RegisterEnum("pb.MoveStatus", MoveStatus_name, MoveStatus_value)
}
