//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: lulu.proto
namespace pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerInfo")]
  public partial class PlayerInfo : global::ProtoBuf.IExtensible
  {
    public PlayerInfo() {}
    
    private int _OID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"OID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int OID
    {
      get { return _OID; }
      set { _OID = value; }
    }
    private string _NickName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"NickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string NickName
    {
      get { return _NickName; }
      set { _NickName = value; }
    }
    private string _HeadIcon;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"HeadIcon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string HeadIcon
    {
      get { return _HeadIcon; }
      set { _HeadIcon = value; }
    }
    private int _Lev;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Lev", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Lev
    {
      get { return _Lev; }
      set { _Lev = value; }
    }
    private int _Exp;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"Exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Exp
    {
      get { return _Exp; }
      set { _Exp = value; }
    }
    private int _Gold;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"Gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Gold
    {
      get { return _Gold; }
      set { _Gold = value; }
    }
    private int _Diamond;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"Diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Diamond
    {
      get { return _Diamond; }
      set { _Diamond = value; }
    }
    private pb.ItemData _Items = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"Items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public pb.ItemData Items
    {
      get { return _Items; }
      set { _Items = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Reward")]
  public partial class Reward : global::ProtoBuf.IExtensible
  {
    public Reward() {}
    
    private int _Exp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Exp
    {
      get { return _Exp; }
      set { _Exp = value; }
    }
    private int _Gold;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Gold
    {
      get { return _Gold; }
      set { _Gold = value; }
    }
    private readonly global::System.Collections.Generic.List<pb.ItemData> _Items = new global::System.Collections.Generic.List<pb.ItemData>();
    [global::ProtoBuf.ProtoMember(3, Name=@"Items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb.ItemData> Items
    {
      get { return _Items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ItemData")]
  public partial class ItemData : global::ProtoBuf.IExtensible
  {
    public ItemData() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _Count;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Count
    {
      get { return _Count; }
      set { _Count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2GSLogin")]
  public partial class C2GSLogin : global::ProtoBuf.IExtensible
  {
    public C2GSLogin() {}
    
    private string _OID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"OID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string OID
    {
      get { return _OID; }
      set { _OID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GS2CLoginRet")]
  public partial class GS2CLoginRet : global::ProtoBuf.IExtensible
  {
    public GS2CLoginRet() {}
    
    private pb.ErrorCode _errorCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"errorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public pb.ErrorCode errorCode
    {
      get { return _errorCode; }
      set { _errorCode = value; }
    }
    private pb.PlayerInfo _playerInfo = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"playerInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public pb.PlayerInfo playerInfo
    {
      get { return _playerInfo; }
      set { _playerInfo = value; }
    }
    private pb.Reward _reward = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"reward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public pb.Reward reward
    {
      get { return _reward; }
      set { _reward = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2GSSwitchMap")]
  public partial class C2GSSwitchMap : global::ProtoBuf.IExtensible
  {
    public C2GSSwitchMap() {}
    
    private int _mapID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mapID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mapID
    {
      get { return _mapID; }
      set { _mapID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GS2CSwitchMapRet")]
  public partial class GS2CSwitchMapRet : global::ProtoBuf.IExtensible
  {
    public GS2CSwitchMapRet() {}
    
    private pb.ErrorCode _errorCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"errorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public pb.ErrorCode errorCode
    {
      get { return _errorCode; }
      set { _errorCode = value; }
    }
    private int _mapID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"mapID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mapID
    {
      get { return _mapID; }
      set { _mapID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GS2CBattleInfo")]
  public partial class GS2CBattleInfo : global::ProtoBuf.IExtensible
  {
    public GS2CBattleInfo() {}
    
    private int _mosterID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mosterID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mosterID
    {
      get { return _mosterID; }
      set { _mosterID = value; }
    }
    private bool _result;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool result
    {
      get { return _result; }
      set { _result = value; }
    }
    private pb.Reward _reward = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"reward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public pb.Reward reward
    {
      get { return _reward; }
      set { _reward = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"ErrorCode")]
    public enum ErrorCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=1)]
      SUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL", Value=2)]
      FAIL = 2
    }
  
}